var NumberOfWords = 98
var words = new BuildArray(NumberOfWords)

// Use the following variables to 
// define your random words:
words[1] = "https://shrinkurl.org/bVwMet" 
words[2] = "https://shrinkurl.org/Pxd0A" 
words[3] = "https://shrinkurl.org/zi98DEgT" 
words[4] = "https://shrinkurl.org/bJdMMD" 
words[5] = "https://shrinkurl.org/Wn8llZ" 
words[6] = "https://shrinkurl.org/y8uUEbj2" 
words[7] = "https://shrinkurl.org/jxBv" 
words[8] = "https://shrinkurl.org/zdqH0wRb" 
words[9] = "https://shrinkurl.org/PS9aGS" 
words[10] = "https://shrinkurl.org/E5GGwIcG" 
words[11] = "https://shrinkurl.org/3GNYQG8" 
words[12] = "https://shrinkurl.org/PtlE1" 
words[13] = "https://shrinkurl.org/Y6q3J" 
words[14] = "https://shrinkurl.org/1FQiX" 
words[15] = "https://shrinkurl.org/vpqlM" 
words[16] = "https://shrinkurl.org/3IKX7" 
words[17] = "https://shrinkurl.org/kGJbU" 
words[18] = "https://shrinkurl.org/80STjyp" 
words[19] = "https://shrinkurl.org/y7WHxc" 
words[20] = "https://shrinkurl.org/Yxy2T4ez" 
words[21] = "https://shrinkurl.org/wpXBT7iJ" 
words[22] = "https://shrinkurl.org/5zVd8O8" 
words[23] = "https://shrinkurl.org/75FE7vR" 
words[24] = "https://shrinkurl.org/gfvSe7" 
words[25] = "https://shrinkurl.org/nJJyM" 
words[26] = "https://shrinkurl.org/Scj423e" 
words[27] = "https://shrinkurl.org/YYJN" 
words[28] = "https://shrinkurl.org/4fYWASgq" 
words[29] = "https://shrinkurl.org/k2AtIT1W" 
words[30] = "https://shrinkurl.org/PDMq1sE" 
words[31] = "https://shrinkurl.org/z0K0JBE" 
words[32] = "https://shrinkurl.org/UdAz0" 
words[33] = "https://shrinkurl.org/TnDSUxpH" 
words[34] = "https://shrinkurl.org/XuD8CYA" 
words[35] = "https://shrinkurl.org/7EbbNKZM" 
words[36] = "https://shrinkurl.org/Et5JOgw" 
words[37] = "https://shrinkurl.org/YCnX" 
words[38] = "https://shrinkurl.org/MTvwgHV" 
words[39] = "https://shrinkurl.org/pyFmI" 
words[40] = "https://shrinkurl.org/gShf" 
words[41] = "https://shrinkurl.org/iDP6lQqi" 
words[42] = "https://shrinkurl.org/bicVE" 
words[43] = "https://shrinkurl.org/NCe9" 
words[44] = "https://shrinkurl.org/UUoDBqt" 
words[45] = "https://shrinkurl.org/9yS5" 
words[46] = "https://shrinkurl.org/EXCXI55" 
words[47] = "https://shrinkurl.org/MuFuIY" 
words[48] = "https://shrinkurl.org/PntYkt" 
words[49] = "https://shrinkurl.org/Q0zFTlxy" 
words[50] = "https://shrinkurl.org/pRQg" 
words[51] = "https://shrinkurl.org/y3ezrNjO" 
words[52] = "https://shrinkurl.org/R4lle5C" 
words[53] = "https://shrinkurl.org/29h9" 
words[54] = "https://shrinkurl.org/5UbI" 
words[55] = "https://shrinkurl.org/EKKEIWt" 
words[56] = "https://shrinkurl.org/zGqAMwpV" 
words[57] = "https://shrinkurl.org/aWBC5bsm" 
words[58] = "https://shrinkurl.org/bPbCM" 
words[59] = "https://shrinkurl.org/wXkvVoeg" 
words[60] = "https://shrinkurl.org/Hhs4s2" 
words[61] = "https://shrinkurl.org/jXfr" 
words[62] = "https://shrinkurl.org/4TgGg7" 
words[63] = "https://shrinkurl.org/c072O" 
words[64] = "https://shrinkurl.org/ekqM" 
words[65] = "https://shrinkurl.org/GqZdz" 
words[66] = "https://shrinkurl.org/FXH2Uly" 
words[67] = "https://shrinkurl.org/HQFykKt" 
words[68] = "https://shrinkurl.org/XIptAnA" 
words[69] = "https://shrinkurl.org/KJQiR" 
words[70] = "https://shrinkurl.org/GmgW" 
words[71] = "https://shrinkurl.org/iOIb1" 
words[72] = "https://shrinkurl.org/1Nn1" 
words[73] = "https://shrinkurl.org/mabGwfH" 
words[74] = "https://shrinkurl.org/ipJw" 
words[75] = "https://shrinkurl.org/U36AHfyH" 
words[76] = "https://shrinkurl.org/bDSWc" 
words[77] = "https://shrinkurl.org/j18Vt" 
words[78] = "https://shrinkurl.org/mmwM" 
words[79] = "https://shrinkurl.org/tPnjr" 
words[80] = "https://shrinkurl.org/dVAR" 
words[81] = "https://shrinkurl.org/rLyP" 
words[82] = "https://shrinkurl.org/OSgV4gw" 
words[83] = "https://shrinkurl.org/F203xj" 
words[84] = "https://shrinkurl.org/OJI7Y" 
words[85] = "https://shrinkurl.org/Xw4RCY" 
words[86] = "https://shrinkurl.org/immS16f" 
words[87] = "https://shrinkurl.org/tjINO" 
words[88] = "https://shrinkurl.org/IWQTyca8" 
words[89] = "https://shrinkurl.org/jGis42" 
words[90] = "https://shrinkurl.org/gIl7B2T" 
words[91] = "https://shrinkurl.org/hs6w" 
words[92] = "https://shrinkurl.org/QF11t4CC" 
words[93] = "https://shrinkurl.org/aVBy" 
words[94] = "https://shrinkurl.org/207FYB" 
words[95] = "https://shrinkurl.org/K0nmb" 
words[96] = "https://shrinkurl.org/nca6" 
words[97] = "https://shrinkurl.org/4fdr" 
words[98] = "https://shrinkurl.org/24VgLK" 

function BuildArray(size){
this.length = size
for (var i = 1; i <= size; i++){
this[i] = null}
return this
}

function PickRandomWord(frm) {
// Generate a random number between 1 and NumberOfWords
var rnd = Math.ceil(Math.random() * NumberOfWords)

// Display the word inside the text box
frm.WordBox.value = words[rnd]
}